### ISSUE TITLE
clj-jq ignoring all but first item on a line of input

### ISSUE THREAD

**Issue by charles-dyfis-net** [dainiusjocas/clj-jq#49]
Seen in version 2.1.0:

```console
$ jq -c . <<<'"hello" "world"'  # expected/upstream-compatible behavior
"hello"
"world"
$ clj-jq -c . <<<'"hello" "world"'  # actual behavior
"hello"
```

**Comment by dainiusjocas** [comment]
Thanks for reporting!

It turns out Jackson supports such use cases: https://cowtowncoder.medium.com/line-delimited-json-with-jackson-69c9e4cb6c00

The fix is coming soon.
