### ISSUE TITLE
Unable to pass a JsonNode to stream-processor in args position

### ISSUE THREAD

**Issue by charles-dyfis-net** [dainiusjocas/clj-jq#52]
In trying to implement a service with clj-nix that receives requests in JSON form and sends responses in JSON form, it makes sense to deserialize as little as possible.

However, trying to pass a JsonNode (corresponding with `{"n": 100}` to an expression that uses a variable `$n`) for vars presently results in the following:

```
java.lang.UnsupportedOperationException: nth not supported on this type: IntNode
 at clojure.lang.RT.nthFrom (RT.java:992)
    clojure.lang.RT.nth (RT.java:940)
    jq.api.api_impl$new_scope.invokeStatic (api_impl.clj:154)
    jq.api.api_impl$new_scope.invoke (api_impl.clj:144)
    jq.api$stream_processor.invokeStatic (api.clj:83)
    jq.api$stream_processor.invoke (api.clj:75)
```

**Comment by dainiusjocas** [comment]
Can you help me to reproduce the problem?

Here is what i have right now:
```clojure
((jq.api/stream-processor ".n = $n" {:vars {:n 3}}) (impl/->JsonNode {"n" 100}))
```

**Comment by charles-dyfis-net** [comment]
What I attempted with the above results is roughly...

```
((jq.api/stream-processor ".n = $n" {:vars (impl/->JsonNode {"n" 3})}) (impl/->JsonNode {"n" 100}))
```

**Comment by charles-dyfis-net** [comment]
...so a more proper reproducer would be:

```clojure
((jq.api/stream-processor ".n = $n") (impl/->JsonNode {"n" 100}) {:vars (impl/->JsonNode {"n" 3})})
```

**Comment by dainiusjocas** [comment]
Now I see what is the issue. I've just made a PR with the feature #53
